import { useMemo,useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { Product } from '@shared/schema';
import { buildPlan,parseInventoryCsv,planCsv,type StockRow } from '@/lib/replenishment';
import './replenishment.css';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Replenishment(){
 const {data:products=[],isLoading,isError}=useQuery<Product[]>({queryKey:['/api/products']});
 const [imported,setImported]=useState<StockRow[]|null>(null),[filename,setFilename]=useState(''),[error,setError]=useState('');
 const [leadDays,setLead]=useState(14),[safetyDays,setSafety]=useState(7),[demand,setDemand]=useState(1),[budget,setBudget]=useState(25000),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const rows=useMemo(()=>imported||products.map(p=>({sku:p.sku,title:p.title,stock:p.currentStock,dailySales:p.avgDailySales,unitCost:p.cost})),[imported,products]);
 const plan=useMemo(()=>buildPlan(rows,{leadDays,safetyDays,demand,budget}),[rows,leadDays,safetyDays,demand,budget]);
 const visible=plan.filter(r=>r.needed>0&&`${r.sku} ${r.title}`.toLowerCase().includes(search.toLowerCase()));
 const pageCount=Math.max(1,Math.ceil(visible.length/25));const activePage=Math.min(page,pageCount-1);
 const total=plan.reduce((a,r)=>a+r.spend,0),units=plan.reduce((a,r)=>a+r.quantity,0),gaps=plan.filter(r=>r.unfunded>0).length;
 return <div className="replenishment"><header className="replenishment-heading"><div><span className="workbench-eyebrow">LOGISTICS &amp; INVENTORY ENGINE / DECISION WORKSPACE</span><h1>Stock for what’s next.</h1><p>Turn inventory into a budget-aware replenishment draft.</p></div><span className="data-badge">{imported?'Your CSV · local only':'Sample inventory · not Amazon-connected'}</span></header>
 <section className="import-strip"><div><strong>{imported?filename:'Bring your inventory'}</strong><p>CSV: sku, title, stock, daily_sales, unit_cost. Files stay in this tab; refreshing clears the import.</p></div><label className="import-action">Import CSV<input aria-label="Import inventory CSV" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2_000_000)throw new Error('CSV must be under 2 MB.');const next=parseInventoryCsv(await file.text());setImported(next);setFilename(file.name);setPage(0);setError('');}catch(err){setError(err instanceof Error?err.message:'Import failed');}}}/></label><button onClick={()=>download('inventory-template.csv','sku,title,stock,daily_sales,unit_cost\nEXAMPLE-001,Example product,12,3,8.50')}>Template ↓</button>{imported&&<button onClick={()=>{setImported(null);setFilename('');}}>Use sample</button>}</section>
 {error&&<p role="alert" className="import-error">{error} Existing data has not changed.</p>}
 <section className="scenario-panel"><div><span className="workbench-eyebrow">WHAT-IF SCENARIO</span><h2>Plan before you purchase.</h2><p>No orders are sent. Quantities are estimates, not supplier commitments.</p></div><div className="scenario-inputs"><label>Supplier lead time <b>{leadDays} days</b><input aria-label="Supplier lead time" type="range" min="0" max="60" value={leadDays} onChange={e=>setLead(+e.target.value)}/></label><label>Safety coverage <b>{safetyDays} days</b><input aria-label="Safety coverage" type="range" min="0" max="30" value={safetyDays} onChange={e=>setSafety(+e.target.value)}/></label><label>Demand scenario <b>{Math.round(demand*100)}%</b><input aria-label="Demand scenario" type="range" min="0" max="2" step=".05" value={demand} onChange={e=>setDemand(+e.target.value)}/></label><label>Budget (USD)<input aria-label="Budget USD" type="number" min="0" max="1000000000" value={budget} onChange={e=>setBudget(Math.min(1e9,Math.max(0,Number(e.target.value)||0)))}/></label></div></section>
 <section className="plan-metrics" aria-live="polite"><div><span>Draft spend</span><strong>{money(total)}</strong><small>of {money(budget)} available</small></div><div><span>Funded units</span><strong>{units.toLocaleString()}</strong><small>across {plan.filter(r=>r.quantity>0).length.toLocaleString()} SKUs</small></div><div><span>Unfunded SKUs</span><strong>{gaps.toLocaleString()}</strong><small>still below target coverage</small></div><div><span>Inventory analyzed</span><strong>{rows.length.toLocaleString()}</strong><small>{imported?'Imported rows':'Sample rows'}</small></div></section>
 <section className="plan-table"><div className="table-toolbar"><div><h2>Replenishment queue</h2><p>Shortest stock coverage first · {visible.length.toLocaleString()} results</p></div><input aria-label="Search replenishment" placeholder="Find SKU or product…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><button disabled={!visible.length} onClick={()=>download('replenishment-draft.csv',planCsv(visible))}>Export filtered draft ↗</button></div>
 {isLoading&&!imported?<p>Loading inventory…</p>:isError&&!imported?<p role="alert">Inventory unavailable. Import a CSV to continue.</p>:<div className="table-scroll"><table><thead><tr><th>Product / SKU</th><th>Coverage</th><th>Needed</th><th>Funded</th><th>Cost</th></tr></thead><tbody>{visible.slice(activePage*25,activePage*25+25).map(r=><tr key={r.sku}><td><strong>{r.title}</strong><small>{r.sku}</small></td><td><span className={r.cover<leadDays?'risk-cover':''}>{Number.isFinite(r.cover)?`${r.cover.toFixed(1)}d`:'No demand'}</span></td><td>{r.needed}</td><td>{r.quantity}{r.unfunded>0&&<small>Budget gap: {r.unfunded}</small>}</td><td>{money(r.spend)}</td></tr>)}</tbody></table>{!visible.length&&<p>No replenishment needed for this filter and scenario.</p>}</div>}
 <div className="pagination"><button disabled={activePage===0} onClick={()=>setPage(activePage-1)}>← Previous</button><span>{activePage+1} / {pageCount}</span><button disabled={activePage>=pageCount-1} onClick={()=>setPage(activePage+1)}>Next →</button></div></section>
 <details className="plan-method"><summary>How this plan is calculated</summary><p>Target stock = ceil(daily sales × demand multiplier × (lead time + safety days)). Needed = max(0, target − stock). Budget is allocated in ascending days-of-cover order using unit costs rounded to cents. This greedy policy is transparent, not a profit optimizer. It excludes open purchase orders, supplier minimums, taxes, freight, seasonality, and delivery uncertainty.</p></details></div>;
}
